name: TranslateApp
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        working-directory: ./app
        run: composer install --prefer-dist
      - name: Run Tests
        working-directory: ./app
        run: composer run-phpunit
      - run: docker build --target app -t samiraboud/php-composer:1.1 -f ./php/Dockerfile .
      - run: docker build -t samiraboud/nginx-php:1.0 -f ./nginx/Dockerfile .
      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push samiraboud/php-composer:1.1
      - run: docker push samiraboud/nginx-php:1.0
